package bln.variables;

import org.openqa.selenium.By;



public class Variables {
	
	
	/** Maximum wait time for dynamic waits */
	public static final int maxTimeout 				= 60;
	public static Boolean isIE						= false;
	public static final String browser				= "Firefox";
	public static final String operatingSystem		= "Windows";
//	public static final String emailId 				= "harika@bridgeloannetwork.com";
//	public static final String pswd 				= "Testingdone28$";
	public static final String emailId 				= "preethi.kolavennu@rcncapital.com";
	public static final String pswd 				= "Bmg348-@";
	
	
	
	public static final By pageBody					=  By.tagName("body");
	public static final By logIn_userName_tb		=  By.id("login");
	public static final By logIn_pwd_tb				=  By.id("password");
	public static final By logIn_click_Submit_btn	=  By.id("submit_0");
	public static final By navigate_to_User		    =  By.xpath("//a[contains(text(),'Users')]");
	public static final By Select_RCNCAPTIAL_Lender	=  By.xpath("//h3[contains(text(),'Lenders')]/following-sibling::div/child::div/child::a[contains(text(),'RCN Capital')]");
	public static final By Select_Loan_Officier	    =  By.cssSelector("#lender_assets >div >div >div:nth-of-type(2) >div:nth-child(1)");
	public static final By softPull_Button		    =  By.cssSelector("img[alt='Order Soft Credit Pull']");
	public static final By forum_label		        =  By.xpath("//div[contains(@class, 'form_label') and contains(.//span, '*')]");
	public static final By NewLoan_Forum_FirstName	=  By.cssSelector("#first_name");
	public static final By NewLoan_Forum_LastName   =  By.cssSelector("#last_name");
	public static final By NewLoan_Forum_Address    =  By.cssSelector("input[name='data[TempBorrower][address]']");
	public static final By NewLoan_Forum_City       =  By.cssSelector("#locality");
	public static final By NewLoan_Forum_State      =  By.cssSelector("select[name='data[TempBorrower][state]'] >option[Value='NY']");
	public static final By NewLoan_Forum_Postalcode =  By.cssSelector("#postal_code");
	public static final By NewLoan_Forum_SSN   		=  By.cssSelector("#borrower_social");
	public static final By order_soft_report_button =  By.cssSelector("#order_soft_report");
	public static final By See  					=  By.cssSelector(".ui-dialog-buttonset >button[class='btn btn-primary']");
	public static final By Score   					=  By.cssSelector("#equifax_score");
	public static final By CreateRequest 			=  By.cssSelector("input[value='Create Request']");
	public static final By LoanNum  				=  By.cssSelector(".new_loan_identifier_left >div:nth-child(2)");
	

	//Closing Coordinator
	public static final By Loan_Request_Link       =  By.xpath("//a[contains(text(),'Loan Requests')]");
	public static final By MyProfile_Link	       = By.xpath("//a[contains(text(),'My Profile')]");
	public static final By MyProfile_PhoneNumber   =  By.cssSelector("input[id='ClosingCoordinatorPhone']");
	
	public static final By MyProfile_PhoneNumber_Lender   =  By.cssSelector("input[id='phone']");
	/** Testing Phone Number */
    public static final String gen_phoneNumber 		= "9676874990";
//    public static final String gen_Email 		    = "xxx_blntestemail+2001@gmail.com";
    public static final String gen_Email 		    = "xxx_blntestemail+208015@gmail.com";
    public static final String gen_purchasePrice	= "9676";
    public static final String Lender_Name	        = "Lend some Money Test";
    //public static final By MyProfile_UpdateProfile = By.cssSelector("#ClosingCoordinatorPhone");
    public static final By MyProfile_UpdateProfile = By.cssSelector("#submit_0");
    public static final By MyProfile_UpdateMessage = By.cssSelector(" #custom_error >h4");
    public static final By MyProfile_Cont_Btn = By.cssSelector("#custom_error >a");
    public static final By MyProfile_Email = By.cssSelector("#EntityEmail");
    public static final By MyProfile_SaveSettings  =  By.xpath("(//button[not(contains(@disabled,'disabled'))])[1]");
    public static final By MyProfile_SaveSetting  =  By.xpath("(//button[contains(text(),'Save Settings')])[1]");
    
    
   
    //CC Variables 
    public static final By CC_UpdateMessage 	= By.cssSelector(" #custom_error >h4");
	public static final By CC_Brokerages  		=  By.xpath("//a[contains(text(),'Brokerages')]");
	public static final By CC_Notes  			=  By.cssSelector("div[class='tabulator-table'] >div:nth-of-type(4) >div:nth-of-type(11)");
	public static final By CC_CC 				=  By.xpath("//a[contains(text(),'Closing Coordinators')]");
	public static final By CC_AddCoordinator  	=  By.cssSelector("input[value='Add Coordinator']");
	public static final By CC_FirstName  		=  By.cssSelector("input[id='first_name']");
	public static final By CC_last_name 		=  By.cssSelector("input[id='last_name']");
	public static final By CC_username 			=  By.cssSelector("input[id='username']");
	public static final By CC_ClosingCoordinatorEmail =  By.cssSelector("input[id='ClosingCoordinatorEmail']");
	public static final By CC_ClosingCoordinatorPhone =  By.cssSelector("input[id='ClosingCoordinatorPhone']");
	public static final By CC_second_page		=By.xpath("//a[contains(text(),'Next >>')]");
	public static final By CC_ClosingCoordinatorDetails =  By.cssSelector("tbody tr:last-child");
	public static final By CC_ClosingCoordinatorDelete =  By.cssSelector("tbody tr:last-child td:last-child a:last-child");
	public static final By CC_LoanFee_FiltersList =  By.cssSelector("select[id='filter_fee']");
	public static final By CC_LoanFee 			= By.xpath("//a[contains(text(),'Loan Fees')]");
	public static final By Select_Unpaid  		=  By.xpath("//option[contains(text(),'Unpaid')]");
	public static final By CC_LoanFee_Actions   =  By.cssSelector(".tabulator-group:first-of-type .tabulator-cell:nth-of-type(8)");
	public static final By CC_LoanFee_Actions_Edit =  By.xpath("//option[contains(text(),'Edit')]");
	public static final By CC_LoanFee_Actions_Edit_FeeType=  By.cssSelector("#edit_fee_type:nth-of-type(1)");
	public static final By CC_LoanFee_Actions_Edit_FeeType_options=  By.cssSelector("option[data-unique-id='1']");
	public static final By CC_LoanFee_Actions_Edit_Amount=  By.cssSelector("input[name='edit_amount']");
	public static final By CC_LoanFee_Actions_Edit_SubmitAmount=  By.xpath("//button[contains(text(),'Submit Changes')]");
	public static final By CC_LoanFee_Actions_Delete =  By.xpath("//option[contains(text(),'Delete')]");
	public static final By CC_LoanFee_Actions_CopyURL =  By.xpath("//option[contains(text(),'Copy Direct Payment URL')]");
	public static final By CC_LoanFee_Actions_Select_Amount=  By.xpath("//div[@data-value='$24.98']/following-sibling::div[6]");
	public static final By CC_LoaRequest_Stagnant =By.cssSelector("a[href='/coordinator/loans/loan_applications/view_stagnant']");
	public static final By CC_LoaRequest_Stagnant_Remove =By.cssSelector(".form:nth-of-type(1) button[type='submit']");
	public static final By CC_LoaRequest_Stagnant_LoanDeatil =By.cssSelector(".form:nth-of-type(1) >div:nth-of-type(1)");
	public static final By CC_LoaRequest = By.xpath("//a[contains(text(),'Loan Requests')]");
	public static final By CC_LoaRequest_New = By.xpath("//a[contains(text(),'LOAN REQUESTS')]");
	public static final By new_Tab1	= By.linkText("LOAN REQUESTS");
	public static final By new_Tab	= By.linkText("urlLink");
	public static final By CC_LoaRequest_FirstLoanNumber =By.cssSelector("div[class^='tabulator-row']:nth-of-type(1) div[tabulator-field='loan_application_id']:nth-of-type(2)");
	public static final By CC_LoaRequest_SearchBar =By.cssSelector("#criteria");
	public static final By CC_Loan_SearchBar =By.cssSelector("div[tabulator-field='loan_application_id'] .tabulator-header-filter >input");
	public static final By CC_LoaRequest_SearchButton =By.cssSelector("input[value='Search']");
	public static final By CC_LoaRequest_ResetSearchButton = By.xpath("//button[contains(text(),'Reset Search')]");
	public static final By CC_Lender = By.xpath("//a[contains(text(),'Lenders')]");	
	public static final By CC_Lender_ProgramType =By.cssSelector("select[id='program_types_dropdown']:nth-of-type(1)");
	public static final By CC_Lender_ProgramType_Space =By.cssSelector("input[placeholder='Search By Program']");
	public static final By CC_LoanRequest_Column =By.cssSelector("div[class='tabulator-col tabulator-sortable'] >div[class='tabulator-col-content'] >div[class='tabulator-col-title']");
	public static final By CC_Lender_Search = By.xpath("//div[contains(text(),'Company')]/following-sibling::div//input");
	public static final By CC_Lender_Select = By.xpath("(//div[@tabulator-field='action'])[2]");
	public static final By CC_Lender_SelectAction = By.cssSelector("select[id='action_dropdown']");
	public static final By CC_Lender_ActionValue = By.cssSelector("select[id='action_dropdown'] >option[value='Edit Profile']");
	public static final By CC_Lender_Name = By.cssSelector("input[id='LenderName']");
	public static final By CC_Lender_Save = By.xpath("(//div[@class='col-md-2'])[26]//button[@type='submit']");
	//Elements related to Users
	
	public static final By Borrower_LoanFee 			= By.xpath("//a[contains(text(),'LOAN FEES')]");
	public static final By Borrower_LoaRequest = By.xpath("//a[contains(text(),'LOAN REQUESTS')]");
	public static final By Borrower_MyProfile_Link	 = By.xpath("//a[contains(text(),'MY PROFILE')]");
	public static final By NavigatetoUser = By.xpath("//a[contains(text(),'Users')]");
	public static final By SelectLender = By.xpath("(//a[contains(text(),'RCN Capital')])[1]");
	public static final By SelectBorrower = By.xpath("//a[contains(text(),'Harika Testcase')]");
	public static final By Borrower_CreateLoan = By.cssSelector("img[alt='Create New Request']");
	public static final By Borrower_Application_Purchase = By.xpath("//div[@class='pull-left'] //input");
	public static final By Borrower_Application_UseofFunds = By.xpath("(//div[@class='col-md-12'])[6] //input");
	public static final By Borrower_Application_ExitStrategy = By.xpath(" (//div[@class='col-md-12'])[8] //input");
	public static final By Borrower_AmountRequested = By.cssSelector("#amount_requested");
	public static final By Borrower_PurchasePrice = By.cssSelector("#purchase_price");
	public static final By Borrower_RehabCost= By.cssSelector("#rehab_costs");
	public static final By Borrower_borrowercontribution = By.cssSelector("#borrower_contribution");
	public static final By Borrower_DesiredTerm= By.cssSelector(".select2-selection__arrow");
	public static final By Borrower_DesiredTerm_Dropdown = By.cssSelector("li[id^='select2-desired_terms-result']");
	public static final By Borrower_NextButton2 = By.xpath("(//button[contains(text(),'NEXT')])[2]");
	public static final By Borrower_NextButton1 = By.xpath("(//button[contains(text(),'NEXT')])[1]");
	public static final By Borrower_Address = By.cssSelector("#lookup_address");
	public static final By Borrower_Address1 = By.cssSelector("#property-address");
	public static final By Borrower_Address2 = By.cssSelector("#borrower-address");
	public static final By Borrower_Addresszip = By.cssSelector("#e_zipcode");
	public static final By Borrower_Addressaddress = By.cssSelector("#e_address");
	public static final By Borrower_Addresscity = By.cssSelector("#e_city");
	public static final By Borrower_AddressStatearrow = By.xpath("(//span[@class='select2-selection__arrow'])[6]");
	public static final By Borrower_AddressStateValue= By.xpath("//li[contains(text(),'New York')]");
	public static final By Borrower_AddressOkButton= By.xpath("(//button[contains(text(),'OK')])[1]");
	public static final By Borrower_Addresszip2 = By.xpath("(//input[@id='e_zipcode'])[2]");
	public static final By Borrower_Addressaddress2 = By.xpath("(//input[@id='e_address'])[2]");
	public static final By Borrower_Addresscity2 = By.xpath("(//input[@id='e_city'])[2]");
	public static final By Borrower_PhoneNumber = By.xpath("(//input[@id='primary_phone'])[2]");
	public static final By Borrower_AddressStatearrow2 = By.xpath("(//select[@id='e_state'])[2]");
	public static final By Borrower_AddressStateValue2= By.xpath("(//option[@value='33'])[2]");
	public static final By Borrower_AddressOkButton2= By.xpath("(//button[contains(text(),'OK')])[2]");
	public static final By Borrower_PropertyType = By.cssSelector("input[name='collateral_type_id']");
	public static final By Borrower_Occupancy = By.cssSelector("input[id^='ocupancy']");
	public static final By Borrower_plan_on_living = By.cssSelector("input[id^='will_occupy']:nth-of-type(2)");
	public static final By Borrower_purchasesale = By.cssSelector("input[id^='purchase_sales']");
	public static final By Borrower_AsisValue = By.cssSelector("#asis_value");
	public static final By Borrower_RepairValue = By.cssSelector("#after_repair_value");
	public static final By Borrower_collateralType= By.xpath("//span[@title='Select Collateral Type']/following-sibling::span");
	public static final By Borrower_collateralType_Value = By.cssSelector("li[id^='select2-cb_property_type-result']");
	public static final By Borrower_Lookupaddress = By.cssSelector("#lookup_borrower_address");
	public static final By Borrower_dob = By.cssSelector("#dob");
	public static final By Borrower_flipped_properties = By.cssSelector("#flipped_properties");
	public static final By Borrower_num_rental_properties = By.cssSelector("#num_rental_properties");
	public static final By Borrower_credit_score = By.cssSelector("#credit_score");
	public static final By Borrower_agreement = By.cssSelector("#have_read_tos");
	public static final By SubmitRequest = By.xpath("//button[contains(text(),'SUBMIT REQUEST')]");
	public static final By LOanDeatils  = By.xpath("(//div[@class='row'])[13] /child::div[2]");
	public static final By Borrower_SSN = By.cssSelector("#social_security_number");
	public static final By Borrower_SSN_Submit = By.xpath("//button[contains(text(),'RETRY REQUEST')]");
	public static final By Borrower_FirstLoan = By.xpath("(//div[@tabulator-field='loan_application_id'])[2]");
	public static final By Borrower_FirstAddressLink = By.xpath("(//div[@tabulator-field='address'])[2]//child::a");
	public static final By Borrower_Addlog = By.xpath("(//a[contains(text(),'Add Log')])[2]");
	public static final By Borrower_Addlog_Msg = By.cssSelector("textarea[id='message']");
	public static final By Borrower_Addlog_Inside = By.cssSelector("input[value='Add Log']");
	public static final By Borrower_Message= By.xpath("(//a[contains(text(),'Messages')])[2]");
	public static final By Borrower_Newmessage = By.cssSelector("input[value='Compose New Message']");
	public static final By Borrower_Subject= By.xpath("(//input[@id='Subject'])[2]");
	public static final By Borrower_SelectAll= By.xpath("(//button[contains(text(),'Select All')])[2]");
	
	public static final By Borrower_MessageBody = By.cssSelector("div[class^='ui-dialog-content'] div#message-body textarea");
	public static final By Borrower_SendMessage= By.xpath("//button[contains(text(),'Send message')]");
	public static final By Borrower_cont = By.cssSelector("div#custom_error >a");
	public static final By Borrower_logcheck = By.cssSelector("div[class^='col-lg-3'] .log-viewer >div:nth-child(1)");
	public static final By Borrower_Lead= By.xpath("(//a[contains(text(),'Lead')])[2]");
	public static final By Borrower_comment = By.cssSelector("#comments");
	public static final By Borrower_savecomment = By.cssSelector("input[value='Save Comments']");
	public static final By Borrower_MakePayment = By.xpath("//span[contains(text(),'Make Payment')]");
	public static final By Borrower_LeadInfo= By.xpath("(//a[contains(text(),'Loan Info')])[2]");
	public static final By Borrower_Contacts= By.cssSelector("htmlgroup[class='bln-bs'] >div[class='vtabs-container'] ul[class='nav nav-tabs'] >li:nth-child(3)");
	public static final By Borrower_AddBroker = By.cssSelector("#add_broker");
	public static final By Borrower_searchterm = By.cssSelector("#search_term");
	public static final By Borrower_searchbutton= By.cssSelector("span[id='brokerage_area'] input[value='Search']");
	public static final By Borrower_brokerDropdown= By.cssSelector("select[id='brokerage_id']");
	public static final By Borrower_brokerDropdownValue= By.cssSelector("select[id='brokerage_id'] >option");
	public static final By Borrower_empDropdown= By.cssSelector("select[id='found_employees']");
	public static final By Borrower_empDropdownValue= By.cssSelector("select[id='found_employees'] >option");
	public static final By Borrower_expereince= By.xpath("(//a[contains(text(),'Experience')])[2]");
	public static final By Borrower_addProperty= By.xpath("(//button[contains(text(),'Add Property')])[1]");
	public static final By Borrower_collateraltype= By.xpath("(//span[@role='presentation'])[1]");
	public static final By Borrower_collateraltypeValues=By.cssSelector("li[class='select2-results__option']");
	public static final By Borrower_collateralAddress = By.cssSelector("#mes_address");
	public static final By Borrower_collateralcity = By.cssSelector("#mes_city");
	public static final By Borrower_collateralzipcode = By.cssSelector("#mes_zipcode");
	public static final By Borrower_collateraltitle = By.cssSelector("#mes_entity_name_on_title");
	public static final By Borrower_collateralownership = By.cssSelector("#mes_percent_of_ownership");
	public static final By Borrower_collateralacquisition = By.cssSelector("#mes_acquisition_date");
	public static final By Borrower_Statetype= By.xpath("(//span[@role='presentation'])[2]");
	public static final By Borrower_statustype= By.xpath("(//span[@role='presentation'])[3]");
	public static final By Borrower_save = By.cssSelector("#mes_edit_save");
	public static final By Borrower_budgetHide = By.xpath("(//input[@id='line_item'])[1]");
	public static final By Borrower_budgetHidden = By.cssSelector("div[class='tabulator-tableHolder'] div[tabulator-field='budget_amount']");
	public static final By Borrower_collateralinfoAddress = By.cssSelector("#ci_address1");
	public static final By Borrower_collateralinfocity = By.cssSelector("#ci_city");
	public static final By Borrower_collateralinfozipcode = By.cssSelector("#ci_zipcode");
	public static final By Borrower_infosave = By.cssSelector("#edit_save");
	public static final By Borrower_continue = By.cssSelector("a[title='Continue']");
	public static final By Borrower_checkpage = By.xpath("(//li[@class='active'])[2] //a");
	
	/** Intake Lender*/
	public static final By IntakeLender_employee = By.xpath("//a[contains(text(),'Kelly Farnsworth')]");
	public static final By IntakeLender_Phone = By.cssSelector("#phone");
	public static final By IntakeLender_HeaderNav = By.cssSelector("#loan_menu >li >a");
	public static final By Clients_Link = By.xpath("//a[contains(text(),'Clients')]");
	public static final By IntakeLender_Options = By.xpath("//select[@id='los_actions']//option[contains(text(),'Revert to Lender')]");
	public static final By IntakeLender_Actions_List = By.xpath("(//select[@id='action_dropdown'])[1]//option");
	public static final By IntakeLender_Actions_ClosingStatus = By.xpath("(//select[@id='action_dropdown'])[1]//option[@value='Set Closing Status']");
	
	public static final By IntakeLender_LoanAction_List = By.cssSelector("#los_actions >option");
	public static final By IntakeLender_Actions = By.xpath("(//div[@tabulator-field='actions'])[2]");
	public static final By IntakeLender_OldTabs_List = By.cssSelector(".process-nav-tab");
	public static final String Revert_to_Lender	= "Revert to Lender";
	public static final String Title_Request_Email= "Title Request Email";
	public static final String Add_to_Queue= "Add to Queue";
	public static final String Loan_Settings= "Loan Settings";
	public static final String Financial= "Financial";
	public static final String UnderWriting= "Underwriting";
	public static final String LoanApprovals= "LoanApprovals";
	public static final By IntakeLender_LoanOfficer = By.xpath("//span[@title='Select Loan Officer'])[2]");
	
	/** RCN Capital Lender */
	public static final By RcnCapital_lender = By.xpath("(//a[contains(text(),'RCN Capital')])[2]");
	public static final By RcnCapital_LP = By.xpath("//a[contains(text(),'Devin Lee')]");
	public static final By RcnCapital_Employee = By.xpath("//a[contains(text(),'Employees')]");
	public static final By RcnCapital_Officer = By.xpath("(//a[contains(text(),'Officers')])[1]");
	//public static final By RcnCapital_LoanOfficer = By.cssSelector("div[id='loan_officers'] a[class='jstree-anchor']");
	public static final By RcnCapital_LoanOfficer = By.cssSelector("i[class$='glyphicon-eye-open jstree-themeicon-custom']");
	public static final By Stop_Impersonation = By.cssSelector("input[value='Stop Impersonation']");
	public static final By RcnCapital_LoanOfficer_List = By.cssSelector("span[aria-labelledby='select2-loan_officer-container'] span[class='select2-selection__arrow']");
	
	/**Lender */
	public static final By Lender_Program		 = By.xpath("//div[@class='loan-settings-left']//div[contains(text(),'Loan Program:')]");
	public static final By Lender_refresh		 = By.xpath("//button[contains(text(),'Refresh Tab')]");
	public static final By Lender 				= By.xpath("//a[contains(text(),'Matt Ferrigno')]");
	public static final By Legal 				= By.xpath("//a[contains(text(),'Thomas Smith')]");
	public static final By Lender_LoanSettings  = By.xpath("//a[contains(text(),'Loan Settings')]");
	public static final By Lender_Collateral  = By.xpath("//a[contains(text(),'Collateral')]");
	public static final By Lender_InsuranceCheck = By.cssSelector("#hoi_company");
	public static final By Lender_SearchBar 	= By.xpath("(//div[contains(text(),'Stage')])[2]//following::div[2]//child::input");
	public static final By Lender_PointsBreakDown = By.cssSelector("table[class='loan-settings-points-table'] >tbody >tr >td:nth-of-type(1)");
	public static final By Lender_PurchasePrice = By.cssSelector("input[id='ci_purchase_price']");
	public static final By NavigatetoCrossBrowser = By.xpath("(//a[contains(text(),'Cross Version Dev')])[1]");
	public static final By New_Borrower=By.xpath("//input[@id='EnableBorrowers1']//parent::label");
	public static final By SaveSetting = By.xpath("//button[contains(text(),'Save Settings')]");
	public static final By AddPointSplit = By.cssSelector("button[onclick='add_points_split();']");
	public static final By BrokerInfo = By.cssSelector("input[id='search_term']");
	public static final By Search = By.cssSelector("button[id='submit_1']");
	public static final By Lender_Close = By.cssSelector("div[class='modal-footer'] button[class='close']");
	public static final By Lender_Close_Popup = By.cssSelector("div[id='add-collateral-modal'] div[class='modal-content']");
	public static final By Brokerage_dropdown = By.cssSelector("#brokerage_id");
	public static final By Brokerage_dropdown_Option = By.xpath("//select[@id='brokerage_id'] //option[contains(text(),'Regression Broker')]");
	public static final By Emp_dropdown = By.cssSelector("#found_employees");
	public static final By Emp_dropdown_Option = By.xpath("//select[@id='found_employees'] //option[contains(text(),'Regression Broker 2')]");
	public static final By GuarantorInfo = By.cssSelector("input[id='entity_search_term']");
	public static final By GuarantorSearch = By.cssSelector("button[id='submit_3']");
	public static final By Guarantor_dropdown = By.cssSelector("#contact_entity_id");
	public static final By Guarantor_dropdown_Option = By.xpath("//select[@id='contact_entity_id'] //option[contains(text(),'Sammie Bryant - sambryant@testatt.net')]");
	public static final By Lender_Addresszip = By.cssSelector("#zipcode");
	public static final By Lender_Addressaddress = By.cssSelector("#address");
	public static final By Lender_Addresscity = By.cssSelector("#city");
	public static final By Lender_Collateral_Dropdown = By.cssSelector("#select2-collateral_type_id-container");
	public static final By Lender_Collateral_Dropdown_Option = By.cssSelector("li[id^='select2-collateral_type_id-result']");
	public static final By Lender_PurchaseRef = By.cssSelector("input[id^='TempClientPropertyOwnProperty']");
	public static final By Lender_Action_LoanSettings = By.xpath("//td[contains(text(),'RCN Capital')]//following::td[5]//child::select");
	public static final By Lender_Action_LoanSettings_options = By.xpath("//td[contains(text(),'RCN Capital')]//following::td[5]//child::select//child::option");
	public static final By Lender_PurchaseOriginal = By.cssSelector("#purchase_price");
	public static final By Lender_PurchaseRehabCost = By.cssSelector("#rehab_costs");
	public static final By Lender_PurchaseARV = By.cssSelector("#after_repair_value");
	public static final By Lender_PurchaseAsisValue = By.cssSelector("#asis_value");
	public static final By Lender_AmountRequested = By.cssSelector("#amount_requested");
	public static final By Lender_DesiredTerm = By.cssSelector("#select2-desired_terms-container");
	public static final By Lender_DesiredTerm_Option = By.cssSelector("li[id^='select2-desired_terms-result']");
	public static final By Lender_UseOfFunds = By.cssSelector("#select2-loan_purpose-container");
	public static final By Lender_UseOfFunds_Option = By.cssSelector("li[id^='select2-loan_purpose-result']");
	public static final By Lender_ExitStrategy = By.cssSelector("#select2-exit_strategy-container");
	public static final By Lender_ExitStrategy_Option = By.cssSelector("li[id^='select2-exit_strategy-result']");
	public static final By Lender_LoanOfficer = By.cssSelector("#select2-loan_officer-container");
	public static final By Lender_LoanOfficer_Option = By.cssSelector("li[id^='select2-loan_officer-result']");
	public static final By Lender_LoanProgram= By.cssSelector("#select2-loan_program-container");
	public static final By Lender_LoanProgram_Option = By.cssSelector("li[id^='select2-loan_program-result']");
	public static final By Lender_SubmitRequest = By.cssSelector("#property_save");
	public static final By Lender_AddPointSplit = By.xpath("//button[contains(text(),' Add Points Split ')]");
	public static final By Lender_PaidTo = By.cssSelector("#select2-LoanPointPaidTo-container");
	public static final By Lender_PaidTo_options = By.cssSelector("li[aria-selected='false']");
	public static final By Lender_points = By.cssSelector("#add_points");
	public static final By Lender_Amount = By.cssSelector("#add_amount");
	public static final By Lender_Comments = By.xpath("//input[@id='LoanPointComments']");
	public static final By Lender_AddLoanPoints= By.cssSelector("input[value='Add Loan Points']");
	public static final By Lender_Addlog = By.xpath("(//a[contains(text(),'Add Log')])[1]");
	public static final By Lender_rebate = By.cssSelector("#select2-LoanPointRebatePaidTo-container");
	public static final By Lender_rebate_points = By.cssSelector("li[class='select2-results__option']");
	public static final By Lender_Collateral_Multi = By.xpath("//a[contains(text(),'Multi Unit / Rental Info')]");
	public static final By Lender_Collateral_Tax = By.xpath("//a[contains(text(),'Tax Info')]");
	public static final By Lender_Collateral_Insurance = By.xpath("//a[contains(text(),'Insurance')]");
	public static final By Lender_Collateral_Close = By.xpath("//div[@id='add-collateral-modal']//button[contains(text(),'Cancel')]");
	
	public static final By Lender_hoi_insurance  =  By.cssSelector("#hoi_company");
	public static final By Lender_stage  =  By.cssSelector("div[tabulator-field='stage'] >div:nth-of-type(1) >div:nth-of-type(3)");
	public static final By Lender_Refresh  =  By.xpath("//button[contains(text(),'Refresh Tab')]");
	public static final By Lender_save  =  By.cssSelector("span[id='edit_save']");

	//public static final By Lender_Message= By.xpath("(//a[contains(text(),'Messages')])[1]");
	public static final By Lender_logcheck = By.cssSelector(".form .form_entity:nth-of-type(2) .log_message");
	public static final By Lender_ViewLog = By.cssSelector(".loan_identifier_buttons.new_loan_identifier_log_buttons:nth-of-type(1)>a");
	public static final By Lender_Message = By.cssSelector("a.process-nav-tab.process-nav-messages-tab");
	public static final By Lender_NewMessage = By.xpath("(//input[@id='MessageSubject'])[3]");
	public static final By Lender_ChooseAction = By.cssSelector("#los_actions");
	public static final By Lender_ClonetheLoan = By.cssSelector("select[id='los_actions'] >option[value='13']");
	public static final By Borrower_Details  =  By.cssSelector(".new_loan_identifier_left >div:nth-child(8)");
	public static final By Guarantor_Details  =  By.cssSelector(".new_loan_identifier_left >div:nth-child(11)");
	public static final By LoanAmount_Details  =  By.cssSelector(".new_loan_identifier_left >div:nth-child(17)");
	public static final By LoanFee_Details  =  By.cssSelector(".tabulator-row.tabulator-selectable");
	public static final By LoanFee_Details_values  =  By.cssSelector(".tabulator-cell");
	public static final By Lender_closealert = By.xpath("(//button[@class='close'])[2]");
	public static final By Lender_closealert1  =  By.cssSelector("#add-collateral-modal .modal-content .modal-header .close");
	public static final By Lender_contact = By.xpath("//a[contains(text(),'Contacts')]");
	public static final By Lender_PrimaryGuarantor  =  By.cssSelector("tr[current_entity='4620'] td[role_id='2']");
	public static final By Select_DenyRequest  			= By.cssSelector("select[id='action_dropdown'] >option[value='Deny Request']");
	public static final By DenyRequest_PLLText  			= By.cssSelector("label[id='refer_lebel']");
	public static final By Actions_Lender               	=   By.cssSelector(".tabulator-row.tabulator-selectable.tabulator-row-odd:nth-of-type(1) >div:nth-of-type(1)");
	/**broker */
	public static final By Select_Unassignto_PLL   			= By.cssSelector("select[id='action_dropdown'] >option[value='Refer to BLN']");
	
	public static final By broker_Actions_dropdown 			=  By.cssSelector("select[id='action_dropdown']");
	public static final By Actions_broker               	=   By.cssSelector(".tabulator-row.tabulator-selectable.tabulator-row-odd:nth-of-type(1) >div");
	public static final By Broker					 		=  By.xpath("//a[contains(text(),'Bridge Loan Network')]");
	public static final By Broker_emp 						=  By.xpath("//a[contains(text(),'BLN Team')]");
	public static final By Broker_HoldLoan  		 		=  By.cssSelector(".col-lg-2.col-md-2.hidden-md.normal .buttons.smaller:nth-of-type(1)");
	public static final By Broker_AddcommentsforHold 		=  By.xpath("(//textarea[@id='reason'])[1]");
	public static final By Broker_contforHold				=  By.xpath("(//input[@id='submit'])[1]");
	public static final By LoanFee_Filteroption  			=  By.cssSelector("select[id='SearchFilter']");
	public static final By LoanFee_Filteroption_ShowActive  =  By.cssSelector("#SearchFilter >option[value='4']");
	public static final By Filteroption_ShowActive  		=  By.cssSelector("#SearchFilter >option[value='8']");
	public static final By LoanFee_Filteroption_ShowDenied  =  By.cssSelector("#SearchFilter >option[value='8']");
	public static final By LoanFee_Filteroption_ShowAll  	=  By.cssSelector("#SearchFilter >option[value='1']");
	public static final By Broker_RemoveHold 				=  By.xpath("(//a[contains(text(),'Remove from Hold')])[2]");
	public static final By Broker_Text 					    =  By.cssSelector("#custom_error >h4");
	public static final By Broker_cont 					    =  By.cssSelector("#custom_error >a");
	public static final By Broker_denyRequest 				=  By.cssSelector(".col-lg-2.col-md-2.hidden-md.normal >div >div:nth-of-type(2)");
	public static final By Broker_denyRequest_Reason		=  By.cssSelector("#reasonContainer >div:nth-of-type(2) >form >div:nth-of-type(1) >div:nth-of-type(3) >select");
	public static final By Broker_denyRequest_Reason_option	=  By.cssSelector("	#reasonContainer >div:nth-of-type(2) >form >div:nth-of-type(1) >div:nth-of-type(3) >select >option:nth-of-type(3)");
	public static final By Broker_denyRequest_Reason_cnt	=  By.cssSelector(".container:nth-of-type(3) input[value='Continue']");
	public static final By Broker_stage 					=  By.xpath("(//div[@tabulator-field='stage'])[2]");
	public static final By Broker_loanNumber 				=  By.xpath("(//div[@tabulator-field='loan_application_id'])[2]");
	public static final By Broker_loanNumber1 				=  By.cssSelector(".col-lg-3.col-md-5.normal >div:nth-of-type(1) >div:nth-of-type(2)");
	public static final By Broker_select				    =  By.xpath("(//button[contains(text(),'SELECT')])[1]");
	public static final By RejectrequestReasons 		    =  By.cssSelector("input[type='radio']");
	public static final By Rejectrequest		            =  By.cssSelector("input[value='Reject Request']");
	public static final By Guarantor_Name		            =  By.cssSelector("#lookup_member");
	public static final By Guarantor_Search		            =  By.cssSelector("#search-member");
	public static final By Guarantor_Properties	            =  By.cssSelector("#flipped_properties");
	public static final By Guarantor_rentalProperties	    =  By.cssSelector("#num_rental_properties");
	public static final By Guarantor_accept				    =  By.cssSelector("#have_read_tos");
	public static final By Setting						    =  By.cssSelector("#loan_menu >li:nth-of-type(2) >a");
	public static final By Setting_Company					=  By.cssSelector("#loan_menu >li:nth-of-type(2) >ul >li:nth-of-type(1)  >a");
	public static final By BrokeragePhone					=  By.cssSelector("input[id='BrokeragePhone']");
	public static final By BrokerageSaveButton				=  By.xpath("(//button[@type='submit'])[1]");
	public static final By DeniedLoanList					=  By.xpath("//div[@tabulator-field='stage' and @role='gridcell']");
	public static final By Broker_AddLender				    =  By.cssSelector("#add-broker-lender");
	public static final By Broker_NewLender					=  By.cssSelector("#select2-search-name-select-container");
	public static final By Broker_NewLenderName				=  By.cssSelector(".select2-search.select2-search--dropdown");
	public static final By Broker_LenderAssignment			=  By.xpath("//a[contains(text(),'Lender Assignment')]");
	public static final By Broker_FeatureAccess				=  By.xpath("//a[contains(text(),'Feature Access')]");
	public static final By Broker_NoAutoAssignment			=  By.cssSelector("#BrokerageAutoassignmentN");
	public static final By Broker_AutoAssigntoBLN			=  By.cssSelector("#BrokerageAutoassignmentC");
	public static final By Broker_hardCreditReport			=  By.cssSelector("input[disabled='disabled'][id='cic_credit_enable']");
	public static final By Broker_AddFee					=  By.cssSelector("#add_fee_btn");
	public static final By Broker_Fee						=  By.xpath("(//a[contains(text(),'Fee')])[2]");
	public static final By Broker_SelectFeeType				=  By.cssSelector("li[aria-selected='false'][class='select2-results__option']");
	public static final By Broker_SelectFeeType_Value		=  By.cssSelector("span[aria-labelledby='select2-new_fee_type_id-container'] >span[class='select2-selection__arrow']");
	public static final By Broker_DefaultAmount				=  By.cssSelector("#new_default_amount");
	public static final By Broker_Description				=  By.cssSelector("#new_description");
	public static final By Broker_AddFeeButton				=  By.cssSelector("button[data-role='new-fee']");
	public static final By Broker_RemoveFee					=  By.xpath("(//button[@data-role='remove-fee'])[1]");	
	public static final By Lender_Guarantor			        =  By.cssSelector(".credit-buttons");
	public static final By Auth_URL					        =  By.cssSelector("#notify_url");
	public static final By Auth_dateob					    =  By.cssSelector("#dateob");
	public static final By Auth_SCN					        =  By.cssSelector("#social_input");
	public static final By Lender_Killed				    =  By.cssSelector("#SearchFilter option[Value='7']");
	public static final By Lender_Search_WithDraw			=  By.cssSelector("div[tabulator-field='stage'] input[type='search']");
	public static final By Lending_States					=  By.xpath("//a[contains(text(),'Lending States')]");
	public static final By Property_Type					=  By.xpath("//a[contains(text(),'Property Types')]");
	public static final By Loan_Type					    =  By.xpath("//a[contains(text(),'Loan Types')]");
	public static final By Lendingstates_all				=  By.cssSelector(".col-md-3 input[id='all']");
	public static final By Lendingstates_dakota				=  By.cssSelector("#state_35");
	public static final By LoanType_Select					=  By.cssSelector("#LoanTypeType_8");
	public static final By PropertyType_Select				=  By.cssSelector(".col-md-3 input[id='LoanTypeType_13']");
	public static final By Lendingstates_save			    =  By.cssSelector("#lending-states >div >form >div:nth-of-type(3) >div:nth-of-type(2) >button");
	public static final By LoanType_save			    	=  By.cssSelector("#loan-types >div >form >div:nth-of-type(3) >div:nth-of-type(2) >button");
	public static final By PropertyType_save			    =  By.cssSelector("#property-types >div >form >div:nth-of-type(3) >div:nth-of-type(2) >button");
	
	public static final By Legal_ClosingScheduleText	    =  By.cssSelector("div[class='col-lg-12']  div:nth-of-type(5) div[class='col-lg-5']");
	public static final By Legal_ClosingScheduleCheckbox	=  By.cssSelector("div[class='col-lg-12']  div:nth-of-type(5) div[class='col-lg-7'] input");
	public static final By Legal_SuccessMessage				=  By.cssSelector("#error-message >font >b");
	public static final By Legal_change						=  By.cssSelector("div[class^='tabulator-row']:nth-of-type(1) div[tabulator-field='closer'] .btn.btn-xs.btn-primary");
	public static final By Legal_ClosingSummary				=  By.xpath("(//a[contains(text(),'Closing Summary')])[1]");
	
	public static final By Legal_ClosingSchedule			=  By.cssSelector("#closing-scheduled");
	public static final By Legal_ScheduleText    			=  By.cssSelector("#est_closing_date >span");
	public static final By Legal_AddPointSplit    			=  By.cssSelector("button[onclick='add_points_split();']");
	public static final By Legal_AddPointSplit_Paidto    	=  By.cssSelector("span[aria-labelledby='select2-LoanPointPaidTo-container'] >span.select2-selection__arrow");
	public static final By Email_Detail				   		=  By.cssSelector(".tabulator-col.tabulator-sortable:nth-of-type(3) >div >div.tabulator-header-filter >input");
	public static final By add_employes				  		=  By.cssSelector(".btn.btn-success");
	public static final By first_name			  			=  By.cssSelector("input[id='first_name']");
	public static final By last_name			  			=  By.cssSelector("input[id='last_name']");
	public static final By phone_no			  				=  By.cssSelector("input[id='LenderEmployeePhone']");
	public static final By email_id			  				=  By.cssSelector("input[id='EntityEmail']");
	public static final By add_employee		  				=  By.cssSelector("input[value='Add Employee']");
	public static final By Employee_Detail	  				=  By.xpath("//a[contains(text(),'Employees')]");
	public static final By Edit_Role		  				=  By.xpath("(//div[@tabulator-field='actions'and @class='tabulator-cell'])[1]//child::button");
	public static final By role_employee		  			=  By.cssSelector(".tabulator-col.tabulator-sortable:nth-of-type(5) >div >div:nth-of-type(3) >input");
	public static final By EmployeeIntake			  		=  By.cssSelector("input[id='LenderEmployeePermissionIntake']");
	public static final By UpdateEmployee			  		=  By.cssSelector("input[value='Update Employee']");
	public static final By Loan_Report  				    =  By.xpath("//h2[contains(text(),'Admin Functions')]//following::div//child::ul//child::li//child::a");
	public static final By Admin  				            =  By.xpath("//a[contains(text(),'Admin')]");
	public static final By Loan_executive  				    =  By.xpath("//a[contains(text(),'Troy Stage Dube')]");
	public static final By garunter 				        =  By.xpath("(//div[@tabulator-field='name'and @class='tabulator-cell'])[1]");
	public static final By closing_summary 				    =  By.xpath("//a[contains(text(),' Closing Summary')]");
	public static final By payment_calculator				=  By.xpath("//a[contains(text(),'Payment Calculator')]");
	public static final By Total_monthaly_payment			=  By.xpath("//div[@class='col-sm-12']//child::h3");
	public static final By Feature_acess		            =  By.xpath("//a[contains(text(),'Feature Access')]");
	public static final By Dont_automatically_update		=  By.xpath("input[id='automaticallyUpdateLoanName']");
	public static final By Save_settings		            =  By.xpath("button[id='save_fee_setting_btn']");
	public static final By Continue		                    =  By.xpath("(//a[contains(text(),'Continue')])[6]");
	public static final By Colletral		                =   By.cssSelector("a[class='process-nav-tab process-nav-tab-complete-active']");
	public static final By Adderess_1		                =   By.cssSelector("input[name='ci_address1']");
	public static final By Save		                        =   By.cssSelector("span[class='fake-link submit-active cif_save']");
	public static final By Loan_settings		            =  By.xpath("//a[contains(text(),'Loan Settings')]");
	public static final By Loan_collateral		            =  By.xpath("//a[contains(text(),'Collateral')]");
	public static final By Loan_name	                    =   By.cssSelector("input[name='data[LoanApplication][loan_name]']");
	public static final By Documents	                    =   By.cssSelector("[class='floating-vtabs-container'] .active>a");
	public static final By Copy_documentation	            =   By.cssSelector("button[id='copy_btn']");
	public static final By Copy_box	                        =   By.cssSelector("input[id='url_to_complete']");
	public static final By Exetend_acess	                =   By.cssSelector("button[id='extend_access_btn']");
	public static final By Apprisal	                        =   By.cssSelector("#loan_menu >li:nth-of-type(5) >a");
	public static final By Actions	                        =   By.cssSelector("div[tabulator-field='actions']>.tabulator-col-content");
	public static final By Loan                             =   By.cssSelector("div[tabulator-field='loan_application_id']>.tabulator-col-content>.tabulator-col-title");
	public static final By File                             =   By.cssSelector("div[tabulator-field='file_no']>.tabulator-col-content>.tabulator-col-title");
	public static final By loan_officer                     =   By.cssSelector("div[tabulator-field='loan_officer']>.tabulator-col-content>.tabulator-col-title");
	public static final By Garunteer                        =   By.cssSelector("div[tabulator-field='guarantor']>.tabulator-col-content>.tabulator-col-title");
	public static final By Stage                            =   By.cssSelector("div[tabulator-field='stage']>.tabulator-col-content>.tabulator-col-title");
	public static final By Est_closing_date                 =   By.cssSelector("div[tabulator-field='est_closing_date']>.tabulator-col-content>.tabulator-col-title");
	public static final By Adderess                         =   By.cssSelector("div[tabulator-field='address']>.tabulator-col-content>.tabulator-col-title");
	public static final By Status                           =   By.cssSelector("div[tabulator-field='status']>.tabulator-col-content>.tabulator-col-title");
	public static final By Payment_status                   =   By.cssSelector("div[tabulator-field='payment_status']>.tabulator-col-content>.tabulator-col-title");
	public static final By Amount                           =   By.cssSelector("div[tabulator-field='amount_due']>.tabulator-col-content>.tabulator-col-title");
	public static final By Due_date                         =   By.cssSelector("div[tabulator-field='due_date']>.tabulator-col-content>.tabulator-col-title");
	public static final By date_ordered                     =   By.cssSelector("div[tabulator-field='order_date']>.tabulator-col-content>.tabulator-col-title");
	public static final By Last_updated_time                =   By.cssSelector("div[tabulator-field='last_update_time']>.tabulator-col-content>.tabulator-col-title");
	public static final By Clients		                    =   By.xpath("//a[contains(text( ),'Clients')]");
	public static final By Phone                            =   By.cssSelector("div[tabulator-field='phone']>.tabulator-col-content>.tabulator-col-title");
	public static final By Selecting_1stloan		        =   By.xpath("(//div[@tabulator-field='name' and @class='tabulator-cell'])[1]");
	public static final By Closing_summary1		            =   By.xpath("(//a[contains(text(),'Closing Summary')])[1]");
	public static final By Loan_request                     =  By.xpath("(//a[contains(text(),'Loan Requests')])");
	public static final By Guarantor                        =  By.xpath("(//div[contains(text(),'Guarantor')])");
	public static final By filter_option                    =  By.name("data[Search][filter]");
	public static final By Guarantor_documents1             =  By.xpath("(//a[contains(text( ),'Documents')])[2]");
	public static final By Add_Collateral                   =   By.cssSelector("#add_collateral_not_exist");
	public static final By Address_Collateral               =   By.cssSelector("#lookup_address");
	
	
	
	

	
}
